config/routes.rb
Rails.application.routes.draw do
  root 'markets#show'
  get 'users/new', to: 'users#new', as: :new_user

  resources :markets, only: [:show] do
    member do
      post 'buy', to: "markets#buy"
      post 'sell', to: "markets#sell"
      get 'next_date', to: "markets#next_date"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/market.rb
# == Schema Information
#
# Table name: markets
#
#  id            :bigint           not null, primary key
#  current_date  :date
#  price         :decimal(10, 2)
#  price_history :json
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :bigint
#
# Indexes
#
#  index_markets_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Market < ApplicationRecord
  belongs_to :user

  def calculate_next_date
    new_date = current_date + 1.day

    new_price = VolatilityService.simulate

    update(current_date: new_date, price: new_price)
    price_history << { date: new_date.strftime('%d %b'), price: new_price.to_f }
    save
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :bigint           not null, primary key
#  amount_of_tokens :integer
#  capital          :decimal(10, 2)   default(10000.0)
#  name             :string
#  username         :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  telegram_id      :bigint
#
class User < ApplicationRecord
  # Устанавливаем связь с моделью Market
  has_one  :market, dependent: :destroy

  # Пришлось добавить коллбэк
  after_initialize :set_market

  def buy_tokens(amount_of_dollars, market)
    tokens_to_buy = amount_of_dollars / market.price
    if capital >= amount_of_dollars
      update(capital: capital - amount_of_dollars, amount_of_tokens: amount_of_tokens + tokens_to_buy)
    else
      false
    end
  end

  def sell_tokens(amount_of_dollars, market)
    dollars_to_receive = amount_of_dollars * market.price
    if amount_of_tokens >= amount_of_dollars
      update(capital: capital + dollars_to_receive, amount_of_tokens: amount_of_tokens - amount_of_dollars)
    else
      false
    end
  end

  private

  def set_market
    self.market || create_market
  end

  def create_market
    Market.create(user: self, current_date: 5.years.ago, price: 10)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_market, only: [:show, :buy, :sell, :next_date]

  def show
    @balance = (current_user.capital - 10000.to_d).to_i
  end

  def buy
    if current_user.buy_tokens(params[:amount_of_dollars_for_buying].to_f, @market)
      redirect_to market_path(@market), notice: 'Transaction completed successfully.'
    else
      redirect_to market_path(@market), notice: 'Not enough capital to buy tokens.'
    end

  end

  def sell
    if current_user.sell_tokens(params[:amount_of_tokens_for_selling].to_i, @market)
      redirect_to market_path(@market), notice: 'Transaction completed successfully.'
    else
      redirect_to market_path(@market), notice: "Not enough tokens to sell."
    end
  end

  def next_date
    @market.calculate_next_date

    redirect_to market_path(@market), notice: "Today's date is #{@market.current_date}"
  end

  private

  def set_market
    @market = current_user.market
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvestmentGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/markets/show.html.erb
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<div class="container">
  <div class="chart-container">
    <div id="chart-data"
       data-prices="<%= @market.price_history.last(10).map { |entry| entry['price'] }.join(',') %>"
       data-dates="<%= @market.price_history.last(10).map { |entry| entry['date'] }.join(',') %>">
    </div>
    <div id="line-chart"></div>
  </div>

  <div class="mt-4 mx-auto max-w-md">
    <h2 class="text-xl font-bold">Username: <%= current_user.username %></h2>
    <p class="text-lg">Today date: <%= @market.current_date.strftime('%Y-%m-%d') %></p>
    <p class="text-lg">Price: <%= @market.price %></p>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <%= form_with url: buy_market_path(@market), method: :post, local: true do |form| %>
          <%= form.label :amount_of_dollars_for_buying, "Amount of dollars:", class: 'block text-base font-medium mb-2' %>
          <%= form.number_field :amount_of_dollars_for_buying, step: 'any', class: 'w-full bg-gray-800 text-white h-10 px-3 rounded mb-2' %>
          <%= form.submit "Buy Tokens", class: 'btn btn-green' %>
        <% end %>
      </div>

      <div>
        <%= form_with url: sell_market_path(@market), method: :post, local: true do |form| %>
          <%= form.label :amount_of_tokens_for_selling, "Amount of tokens:", class: 'block text-base font-medium mb-2' %>
          <%= form.number_field :amount_of_tokens_for_selling, step: 'any', class: 'w-full bg-gray-800 text-white h-10 px-3 rounded mb-2' %>
          <%= form.submit "Sell Tokens", class: 'btn btn-red' %>
        <% end %>
      </div>
    </div>
  </div>

  <div id="user-info" class="mt-4 mx-auto max-w-md">
    <p class="text-base">You have: <%= number_with_precision(current_user.capital, precision: 2) %> dollars</p>
    <p class="text-base">You have: <%= current_user.amount_of_tokens %> tokens</p>
  </div>

  <div class="mt-4 w-full max-w-md px-4">
    <%= link_to 'Next Day', next_date_market_path(@market), class: 'btn btn-lime' %>
  </div>


  <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
  <% end %>

</div>
<script>
  function initializeChart() {
    const chartDataElement = document.getElementById("chart-data");
    const prices = chartDataElement.getAttribute("data-prices").split(',').map(Number);
    const dates = chartDataElement.getAttribute("data-dates").split(',');

    const options = {
      series: [{
        name: "Price",
        data: prices,
        color: "#00FF00",
      }],
      chart: {
        height: 300,
        type: "area",
        fontFamily: "Inter, sans-serif",
        dropShadow: {
          enabled: false,
        },
        toolbar: {
          show: false,
        },
      },
      dataLabels: {
        enabled: true,
        style: {
          cssClass: 'text-xs text-white font-medium',
          fontSize: '9px',
          colors: ['#049804'],
        },
        formatter: function (value) {
          return value.toFixed(2);
        }
      },
      stroke: {
        width: 2,
      },
      grid: {
        show: true,
        strokeDashArray: 4,
        padding: {
          left: 16,
          right: 16,
          top: 0,
        },
      },
      tooltip: {
        enabled: true,
        x: {
          show: false,
        },
      },
      fill: {
        type: "gradient",
        gradient: {
          opacityFrom: 0.55,
          opacityTo: 0,
          shade: "#00FF00",
          gradientToColors: ["#00FF00"],
        },
      },
      xaxis: {
        categories: dates,
        labels: {
          show: true,
          style: {
            colors: '#FFFFFF',
            fontFamily: "Inter, sans-serif",
            cssClass: "text-xs font-normal",
          },
        },
        axisBorder: {
          show: false,
        },
        axisTicks: {
          show: false,
        },
      },
      yaxis: {
        show: false,
      },
    };

    const chartElement = document.querySelector("#line-chart");
    if (chartElement) {
      chartElement.innerHTML = '';
      const chart = new ApexCharts(chartElement, options);
      chart.render();
    }
  }

  document.addEventListener("DOMContentLoaded", initializeChart);
</script>

app/views/users/index.html.erb
<style>
  body {
    background-color: white;
  }
</style>

<h1>Профиль пользователя</h1>

<% if @user %>
  <p>ID: <%= @user.telegram_id %></p>
  <p>Имя: <%= @user.name || 'Не указано' %></p>
  <p>Имя пользователя: <%= @user.username || 'Не указано' %></p>
<% else %>
  <p>Пользователь не найден</p>
<% end %>